---
- name: Install Node.js 16 on Amazon Linux
  hosts: all
  become: yes

  tasks:
    - name: Install Node.js 16 package
      yum:
        name: nodejs16
        state: present

    - name: Install npm
      yum:
        name: npm
        state: present

    - name: Verify Node.js and npm installation
      command: >
        node --version && npm --version

